### ISSUE TITLE
Does not work without specifying options

### ISSUE THREAD

**Issue by websirnik** [farmatholin/SegmentIoBundle#2]
If have the following config:

``` yaml
# SegmentIoBundle Configuration
segment_io:
    write_key: "%your_key%"
```

I got the following error during the bootstrap:

```
Undefined index: options in .../vendor/farmatholin/segment-io-bundle/DependencyInjection/SegmentIoExtension.php on line 29
```
